version: '3.8'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: prep_app
        volumes:
            - .:/var/www/html
        networks:
            - prep_network
        depends_on:
            - redis
    queue:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: prep_queue
        volumes:
            - .:/var/www/html
        networks:
            - prep_network
        depends_on:
            - redis
            - app
        command: php artisan queue:work --tries=3

    nginx:
        image: nginx:latest
        container_name: prep_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - prep_network

    mysql:
        image: mysql:8.0
        container_name: prep_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: prep_database
            MYSQL_USER: quang
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - prep_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: prep_phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - prep_network

    redis:
        image: redis:latest
        container_name: prep_redis
        ports:
            - "6379:6379"
        networks:
            - prep_network
        volumes:
            - redis_data:/data
volumes:
    mysql_data:
    redis_data:

networks:
    prep_network:
